# Cryptostore sample config file for Docker

cache: redis

redis:
    ip: redisdb
    port: 6379
    del_after_read: true
    start_flush: true

exchanges:
    BITMEX:
        l2_book: [XBTUSD]
        trades: [XBTUSD]
    COINBASE:
        l2_book: [BTC-USD]
        trades: [BTC-USD, ETH-USD, ETH-BTC]

book_depth: null
book_delta: True

storage: [arctic]
arctic: mongodb://mongo:27017

storage_interval: 60

plugins:
  backfill:
    module: [cryptostore.plugin.backfill, Backfill]
    config: config.yaml

backfill:
    COINBASE:
        BTC-USD:
            start: '2017-01-01'
